# NumPy Random

In [1]:
import numpy as np

In [2]:
rg = np.random.default_rng()

## Floats

In [3]:
rg.random()

0.11432963479711888

In [4]:
rg.random(5)

array([0.90932212, 0.48552812, 0.8262711 , 0.48604828, 0.26718589])

In [5]:
rg.random((4, 2))

array([[0.39802666, 0.37033862],
       [0.46525811, 0.34355214],
       [0.35331676, 0.75073855],
       [0.43492641, 0.852152  ]])

## Integers

In [6]:
rg.integers(1, 7, 4)

array([2, 3, 6, 1])

In [13]:
rg.integers(0, 256, (4, 4), dtype=np.uint8)

array([[ 12,  77,  19, 244],
       [235, 243, 249, 220],
       [209, 238,  40,  21],
       [201,  15, 183,  83]], dtype=uint8)

## Bytes

In [8]:
rg.bytes(10)

b'U\xa9\xf3\x8c\xa31n@\xfd\x1b'

## Shuffle Array

In [9]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
rg.shuffle(a)
a

array([7, 4, 3, 8, 1, 9, 5, 0, 2, 6])