# NumPy Arrays: Slicing

In [16]:
import numpy as np

## 3x3 RGB Image

- 3 rows
- 3 columns
- every element consists of 3 bytes (RGB)

In [17]:
pixels = np.array([[[1,11,111],[2,22,222],[3,33,333]], [[4,44,444],[5,55,555],[6,66,666]], [[7,77,777],[8,88,888],[9,99,999]]])
pixels

array([[[  1,  11, 111],
        [  2,  22, 222],
        [  3,  33, 333]],

       [[  4,  44, 444],
        [  5,  55, 555],
        [  6,  66, 666]],

       [[  7,  77, 777],
        [  8,  88, 888],
        [  9,  99, 999]]])

### Return the middle RGB byte of each pixel as a flat list

`...` is shorthand and inserts as many `:` in the index as necessary.

In [18]:
pixels[:,:,1]

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [19]:
pixels[:,:,1].flatten()

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [20]:
pixels[...,1].flatten()

array([11, 22, 33, 44, 55, 66, 77, 88, 99])