# NumPy Arrays: Indexing

In [70]:
import numpy as np

## Using an integer Array index

https://numpy.org/doc/stable/user/quickstart.html#indexing-with-arrays-of-indices

The integer indices define the values that should be returned.

### Index 1D Array with another 1D Array

Returns a 1D array.

In [71]:
squares = np.arange(1, 17)**2
idx = np.array([1, 3, 5, 7])
print(squares)
print(idx)
print(squares[idx])

[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256]
[1 3 5 7]
[ 4 16 36 64]


### Index 1D Array with a 2D Array

Returns a 2D array.

In [72]:
squares = np.arange(1, 17)**2
print(squares)

[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256]


In [73]:
idx = np.array([[1, 3], [5, 7]])
idx

array([[1, 3],
       [5, 7]])

In [74]:
squares[idx]

array([[ 4, 16],
       [36, 64]])

### Index 2D Array with a 1D Array

Indexes the rows.

In [75]:
squares = np.arange(1, 17).reshape((4, 4))**2
squares

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [76]:
idx = np.array([1, 3])
squares[idx]  # returns the 2nd and 4th row

array([[ 25,  36,  49,  64],
       [169, 196, 225, 256]])

## Using a Boolean Array index

https://numpy.org/doc/stable/user/quickstart.html#indexing-with-boolean-arrays

If the Boolean array has the same size/shape as the array to be indexed, the values where the index is `True` will be returned.

### 1D Arrays

In [77]:
numbers = np.arange(10)
idx = numbers > 4
print(numbers)
print(idx)
print(numbers[idx])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]


### 2D Arrays

In [78]:
numbers = np.arange(1, 17).reshape((4, 4))
print(numbers)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [79]:
idx = numbers % 5 == 0
print(idx)

[[False False False False]
 [ True False False False]
 [False  True False False]
 [False False  True False]]


In [80]:
print(numbers[idx])

[ 5 10 15]


### Assign new values

Overwrite all values where the index is `True`.

In [81]:
numbers[idx] = 999
print(numbers)

[[  1   2   3   4]
 [999   6   7   8]
 [  9 999  11  12]
 [ 13  14 999  16]]
