# NumPy Arrays

In [95]:
import numpy as np

## Array Infos

In [96]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], np.int16)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [97]:
print("    type:", type(a))
print("    ndim:", a.ndim)
print("   shape:", a.shape)
print("    size:", a.size)
print("   dtype:", a.dtype)
print("itemsize:", a.itemsize)
print("  nbytes:", a.nbytes)

    type: <class 'numpy.ndarray'>
    ndim: 2
   shape: (2, 4)
    size: 8
   dtype: int16
itemsize: 2
  nbytes: 16


## Create Arrays

The `shape` parameter is either an `int` (number of elements) or a tuple for the dimensions.

### Don't initialize the Array values

In [98]:
np.empty(8)

array([0.e+000, 0.e+000, 1.e-323, 0.e+000, 0.e+000, 0.e+000, 0.e+000,
       0.e+000])

### Initialize Array with a fixed value

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [103]:
np.full(10, 42)

array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42])

In [104]:
np.full((4, 4), "four")

array([['four', 'four', 'four', 'four'],
       ['four', 'four', 'four', 'four'],
       ['four', 'four', 'four', 'four'],
       ['four', 'four', 'four', 'four']], dtype='<U4')

### Arrays with existing data

In [105]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [106]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
np.array([1, 2, 3, 4, 5], np.uint8)

array([1, 2, 3, 4, 5], dtype=uint8)

In [108]:
np.array(range(8))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [109]:
np.array([x*x for x in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [110]:
it = iter([1, 2, 3])
np.fromiter(it, np.float32)

array([1., 2., 3.], dtype=float32)

### Copy Array

In [111]:
a = np.arange(10)
b = a.copy()
a.fill(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ranges

In [112]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.arange(20, 30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [114]:
np.arange(10, 110, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [115]:
np.linspace(0, 2, 9)  # evenly spaced numbers over a specified interval

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Transform Arrays

In [116]:
np.arange(1, 17).reshape((4, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
np.arange(1, 17).reshape((2, 8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [118]:
np.array([[1, 2], [3, 4]]).flatten()

array([1, 2, 3, 4])

In [119]:
np.arange(1, 17).reshape((4, 4)).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [120]:
# .flat is an iterator over all elements
for n in np.arange(1, 5).reshape((2, 2)).flat:
    print(n)

1
2
3
4


### Transform automatically

If a parameter is `-1` in a `.reshape()` call, the necessary size will be calculated automatically.

In [121]:
np.arange(12).reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.arange(12).reshape((-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Rounding

In [123]:
a = np.array([1.0, 1.3, 1.5, 1.7, 2.0])
print(a)
print(a.round())
print(a.round().astype(int))
print(a.astype(int))

[1.  1.3 1.5 1.7 2. ]
[1. 1. 2. 2. 2.]
[1 1 2 2 2]
[1 1 1 1 2]


## Array calculations

In [124]:
a = np.arange(1, 11)
b = np.arange(10, 110, 10)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]


In [125]:
print(a + b)
print(a * b)

[ 11  22  33  44  55  66  77  88  99 110]
[  10   40   90  160  250  360  490  640  810 1000]


In [126]:
3 * b

array([ 30,  60,  90, 120, 150, 180, 210, 240, 270, 300])

In [127]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [128]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [129]:
10 * np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495, -9.58924275,
       -2.79415498,  6.56986599,  9.89358247,  4.12118485, -5.44021111])

## Assign new values

In [130]:
c = np.ones(8, int)
c[2] = 3
print(c)

[1 1 3 1 1 1 1 1]


In [131]:
c *= 9
print(c)

[ 9  9 27  9  9  9  9  9]


In [132]:
c[:-3]

array([ 9,  9, 27,  9,  9])

In [133]:
c = np.empty(4, int)
c.fill(3)
c

array([3, 3, 3, 3])

## Type Conversion

In [134]:
a = np.arange(5, dtype=np.float32)
a

array([0., 1., 2., 3., 4.], dtype=float32)

In [135]:
a.astype(np.uint8)

array([0, 1, 2, 3, 4], dtype=uint8)